name: Trigger Terraform Workflow

on:
  workflow_dispatch:

jobs:
  trigger-terraform:
    uses: venkatkumarp/main-workflows/.github/workflows/test-workflow.yml@main
    with:
      aws_region: us-east-1
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
