import { HttpClient, HttpEvent, HttpHeaders } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable, of} from 'rxjs';
const httpOptions = {
  headers: new HttpHeaders({
    'Content-Type': 'application/json'
  })
};

@Injectable({
  providedIn: 'root'
})
export class APIService {

  constructor(private http: HttpClient,) { }

  searchByEmail(data: string): Observable<any[]> {
     // This is Test Fuction, will be removed after testing as currently we don't have proper APIs Created yet
    // return this.http.get<any[]>('https://jsonplaceholder.typicode.com/posts', httpOptions)
    //   .pipe(
    //     catchError((error)=>{
    //       return throwError(() => new Error(error));
    //     }
    //   ));
    return of([{
      "fullName": "Test, User",
      "title": "QWERT",
      "status": "0",
      "email": "user.test.ext@bayer.com"
  },{
      "fullName": "Test1, User",
      "title": "QWERT",
      "status": "1",
      "email": "user.test.ext@bayer.com"
  },{
      "fullName": "Tes2, User",
      "title": "QWERT",
      "status": "2",
      "email": "user.test.ext@bayer.com"
  }]);
  }
  getUserData(email:string){
    return of([ {
      "title": "USER.TEST@BAYER.COM",
      "emailAddress": "user.test@bayer.com",
      "cwid": "ABCDE",
      "company": "Cognizant",
      "hoursWeek": 40,
      "roles": [
          "GDSA Clinical Data Reviewer"
      ],
      "country": "Usa",
      "legalEntity": "BHCP Inc/USA",
      "topFunction": "PH Research&Dev.",
      "subFunction": "CDPE",
      "subSubFunction": "CDPE-DMOI",
      "backupId": null,
      "timekeepingAssistantId": "user.test1@bayer.com",
      "timekeepingAssistant2Id": null,
      "employeeStartDate": "2022-03-01",
      "employeeEndDate": null,
      "selfApprover": "no",
      "fullName": "User, Test",
      "supervisorId": "user.test@bayer.com",
      "costCenter": "G353/E413267412",
      "function": "CD&O",
      "externalFlag": "yes",
      "isExistingUser": true
  }])
  }

  getCompany(){
    return of([
      "3rd Party Ltd",
      "AIXIAL",
      "ALCHEMICS",
      "AO",
      "AVIAD",
      "Abylsen GmbH",
      "Acora Pharma GmbH",
      "Adecco Personaldienstleistungen GmbH",
      "Aerotek",
      "Allied Clinical Management",
      "Allied Clinical Management GmbH",
      "Apo Plus Station CO LTD",
      "BAYER",
      "BAYER AG",
      "BDR Associates",
      "BESTAT PHARMASERVICES CORP",
      "BPPL",
      "Bayer",
      "Bayer (contractor: US Tech Solutions, Inc.)",
      "Bayer AG",
      "Bayer Healthcare Company Limited",
      "Bayer Zydus",
      "Belcan",
      "Belcan Corporation",
      "Bexon Clinical Consulting",
      "BioCodex Oy",
      "Biovian Oy",
      "Blue Eskimo",
      "Blue Pelican",
      "Bright Plus Outsourcing solutions",
      "Bright Prospect Services Sdn Bhd",
      "Brunel GmbH",
      "CAC Croit Corporation",
      "CHU Lille",
      "CMIC HOLDINGS Co Ltd",
      "COVANCE",
      "CPL Life Sciences",
      "Captativa Consultoria E Recursos Humanos Ltda",
      "Chiltern",
      "Chrestos Concept GmbH",
      "ClinBAY sprl",
      "ClinStat GmbH",
      "Clinbay â¢ Bayer Pharma-PH-RND-T&AM",
      "Clinical Professionals Ltd",
      "Clinres Farmacija",
      "Cognizant",
      "Cognizant Consulting and Services GmbH",
      "Complete Regulatory",
      "Computer Sciences Corporation",
      "Computer Task Group",
      "Consult 10",
      "Corporate Employment Resources",
      "Corporate Employment Resources, Inc",
      "Covance",
      "Crown",
      "Crown CRO",
      "Crown CRO Oy",
      "Crown Oy",
      "Cutterwick",
      "DAIN Studios GmbH",
      "DOCS",
      "DRA Consulting",
      "DataFocus",
      "DataFocus GmbH",
      "Development Beijing PH BHC Company Ltd",
      "Development Beijing, Pharmaceuticals",
      "Development Beijing, Pharmaceuticals, Bayer Healthcare Company Limited",
      "Dilphi Corporation",
      "Dr Notghi Contract Research GmbH",
      "EPS",
      "EXALON GmbH",
      "Edge Recruitment Resources",
      "Elite Personnel",
      "Enterprise Solutions",
      "Entourage GmbH",
      "Experis",
      "Express Personnel",
      "External Company",
      "Fairleigh Dickinson University",
      "Farenta Oy",
      "Fern Valley",
      "Fortrea",
      "Fortrea (former LabCorp)",
      "Forum Jobs Vilvoorde",
      "GENPACT",
      "GGROUP",
      "Gallandeer Ridge Pty Ltd",
      "Genpact Pharmalink",
      "Germany",
      "Gess Partner",
      "Gloor Lang AG",
      "GraphiCode",
      "Guidant Global",
      "HAYS",
      "HR UNIVERSAL GmbH",
      "HRC Group",
      "HRCV",
      "Hangzhou Tigermed Consulting",
      "Hays Temp GmbH",
      "Herrmann GmbH",
      "Herrmann Personaldienste GmbH",
      "Hobson Prior",
      "Howard University",
      "Hudson",
      "Hunter International, Inc",
      "ICM Taiwan Ltd",
      "ICON",
      "ICON (formerly PRA)",
      "ICON PLC",
      "ICON/PRA",
      "ICONMA LLC",
      "IMC",
      "ISS",
      "Impres",
      "Instinct Resourcing Limited",
      "Inventiv",
      "JCW Search Limited",
      "Jobactive",
      "Jobis",
      "Joule Inc",
      "KCR SA",
      "KUL",
      "Kelly Services",
      "LABCORP",
      "LS",
      "LabCorp",
      "Labcorp",
      "Linical Co Ltd",
      "Lorenz Archiv Systeme GmbH",
      "Lorenz Life Sciences GmbH",
      "Lugera and Makler srl Bucharest",
      "MEDISCIENCE PLANNING Inc",
      "META RH",
      "MNPM",
      "Manpower",
      "Manpower Group",
      "ManpowerGroup",
      "Medfiles SIA",
      "MediGno Oy",
      "Mejora Continua",
      "Mybest Group S p A",
      "Nanjing Maida Medical ScienceTechnology co Ltd",
      "Neox S r o",
      "Neues Co LTD",
      "Next Phase Recruitment",
      "NextPhase",
      "OGRIN",
      "OGRINA",
      "ORIGIN",
      "OnQ",
      "Optimapharm Nordic",
      "Oriola Finland Oy",
      "PAREXEL International Corp",
      "PASONA",
      "PERSOL TEMPSTAFF CO LTD",
      "PERSOL TEMPSTAFF CO LTD.",
      "PPD Germany GmbH und Co KG",
      "PPD SNBL",
      "PRA Health Sciences",
      "PRA HealthServices",
      "PRAH",
      "PRAHS",
      "PeopleSearch Pte Ltd",
      "Peoplelink LLC",
      "Perficient",
      "Permacon GmbH",
      "Pharma Relations",
      "Pharma Services Oehler GmbH",
      "PharmaLex GmbH",
      "Pharmaceutical & Medical Professionals Pty Ltd",
      "Pharmalex",
      "Pharmalex GmbH",
      "Pharmalink Services Europe GmbH",
      "Pharmica Consulting",
      "Premiere",
      "ProClinical",
      "ProJob 21",
      "ProPharma Group GmbH",
      "Qualitis",
      "Quess Corp",
      "Quintiles",
      "RPS Research Iberica",
      "RTrack Consulting AB",
      "Randstad",
      "Randstad Deutschland GmbH & Co. KG",
      "ReSearch Pharmaceutical Services Inc",
      "Real Staffing",
      "Recruit Holdings Co Ltd",
      "Reed",
      "Rose International, Inc",
      "Rutgers PharmD Fellow",
      "Rutgers University",
      "S Cubed",
      "S2 ScienceSolutions",
      "SCA",
      "SLS Services Ltd",
      "STA PACIFIC",
      "SThree Temp Experts GmbH",
      "Saltarelo Limited",
      "Scientific Solutions",
      "Secret Files Oy",
      "Skillpower Services Thailand Co Ltd",
      "Skills Alliance",
      "Staburo",
      "StatFinn Oy",
      "Syncwork AG",
      "Syndicus Inc",
      "Syndicus, Inc.",
      "Syneos",
      "Syneos Health",
      "Synergie",
      "TCS",
      "TCS Deutschland GmbH",
      "TFS Trial For Support Oy",
      "TRIMES OY",
      "Takumi Information Technology Inc",
      "Talent-net GmbH",
      "Talentnet",
      "Talentnet GmbH",
      "Taylored Training Ltd",
      "Technicon",
      "Technopro",
      "Temporing SL",
      "Tigermed Consulting Co Ltd",
      "Trenkwalder",
      "Turun yliopisto",
      "US Tech",
      "US Tech Solutions Inc",
      "Umanis",
      "VMP Varamiespalvelu Staffservice Finland Oy",
      "WDB CO LTD",
      "Wincere Inc",
      "World Intec co LTD",
      "Xendo Deutschland GmbH",
      "Yoh",
      "Yoh Services",
      "Zing",
      "Zing Professional",
      "accerise Inc",
      "aspark medical",
      "bitworkers",
      "bitworkers GmbH",
      "complete regulatory",
      "inVentiv Health Clinical",
      "intilaris LifeSciences",
      "labcorp",
      "svelte scientific"
  ])
  }

  getSubSubFunction(costCenter: string){
    return of([
      "CDPE",
      "CDPE-SPA",
      "CDPE-DMOI",
      "CDPE-CDM",
      "CDPE-CDP",
      "CSA"
  ])
  }

  getCostCenter(costCenter:string){
    return  of([
      {
          "costCenter": "G353/E413267412",
          "legalEntity": "BHCP Inc/USA",
          "function": "CD&O",
          "subFunction": "CDPE",
          "topFunction": "PH Research&Dev.",
          "country": "Usa"
      },{
          "costCenter": "G353/E413267412",
          "legalEntity": "BHCP Inc/USA",
          "function": "CD&O",
          "subFunction": "CDPE",
          "topFunction": "PH Research&Dev.",
          "country": "Usa"
      }
  ])
  }

  getRoles(roleQuery: string){
    return of(["Role1","Role2"])
  }
}
